# Generated by Django 4.2 on 2025-03-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_category_date_creation_category_date_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='birthday',
            new_name='date_birthday',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='sexo',
            new_name='gender',
        ),
    ]
